// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTranning.Models;

namespace TaskTranning.Migrations
{
    [DbContext(typeof(CodeFirstDataContext))]
    [Migration("20190523074112_AddUser")]
    partial class AddUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskTranning.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("PassWord");

                    b.Property<int>("Phone");

                    b.Property<string>("Picture");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "18/11 Thuy Tu",
                            Email = "khanhtmd97@gmail.com",
                            FullName = "Nguyen Van Khanh",
                            IsActive = true,
                            PassWord = "10000:NmhiNuWZVWqp4PFYlC9V8hfOXAqDa+xuHdGBpfAwYHLTre/w",
                            Phone = 364606406,
                            Picture = "logo.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "25/23/131 Tran Phu",
                            Email = "hoaithu1486@gmail.com",
                            FullName = "Tran Thi Hoai Thu",
                            IsActive = true,
                            PassWord = "10000:UIG0luYxLNx5HpwbfiLtaHHJbZIgW/v8IbLPS/pOmIbM+E8b",
                            Phone = 364606406,
                            Picture = "logo.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
