// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTranning.Models;

namespace TaskTranning.Migrations
{
    [DbContext(typeof(CodeFirstDataContext))]
    [Migration("20190523074432_AddStore")]
    partial class AddStore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskTranning.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<int>("Phone");

                    b.Property<string>("State");

                    b.Property<string>("StoreName");

                    b.Property<string>("Street");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hue City",
                            Email = "khanhtmd99@gmail.com",
                            Phone = 364606406,
                            State = "",
                            StoreName = "KhanhStore",
                            Street = "18/11 Thuy Tu",
                            ZipCode = "49000"
                        },
                        new
                        {
                            Id = 2,
                            City = "Hue City",
                            Email = "Loc97@gmail.com",
                            Phone = 364606406,
                            State = "",
                            StoreName = "LocStore",
                            Street = "18/11 Thuy Tu",
                            ZipCode = "49000"
                        },
                        new
                        {
                            Id = 3,
                            City = "Hue City",
                            Email = "Huan97@gmail.com",
                            Phone = 364606406,
                            State = "",
                            StoreName = "HuanStore",
                            Street = "18/11 Thuy Tu",
                            ZipCode = "49000"
                        },
                        new
                        {
                            Id = 4,
                            City = "Hue City",
                            Email = "Tuan97@gmail.com",
                            Phone = 364606406,
                            State = "",
                            StoreName = "TuanStore",
                            Street = "18/11 Thuy Tu",
                            ZipCode = "49000"
                        });
                });

            modelBuilder.Entity("TaskTranning.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("PassWord");

                    b.Property<int>("Phone");

                    b.Property<string>("Picture");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "18/11 Thuy Tu",
                            Email = "khanhtmd97@gmail.com",
                            FullName = "Nguyen Van Khanh",
                            IsActive = true,
                            PassWord = "10000:ILQ20u8uF4q0MWjoKY9TRjPaw2FIFlv3PNdZTGqEfACVv4ah",
                            Phone = 364606406,
                            Picture = "logo.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "25/23/131 Tran Phu",
                            Email = "hoaithu1486@gmail.com",
                            FullName = "Tran Thi Hoai Thu",
                            IsActive = true,
                            PassWord = "10000:a2soGsfxpdIC3xG/HYe4Vc43K/QX7MyxWx5zR6OZUWnyFS+W",
                            Phone = 364606406,
                            Picture = "logo.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
