//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_TitleCategory {
            get {
                return ResourceManager.GetString("lbl_TitleCategory", resourceCulture);
            }
        }
        
        public static string lbl_Categories {
            get {
                return ResourceManager.GetString("lbl_Categories", resourceCulture);
            }
        }
        
        public static string lbl_CategoryName {
            get {
                return ResourceManager.GetString("lbl_CategoryName", resourceCulture);
            }
        }
        
        public static string lbl_TitleCreateCustomer {
            get {
                return ResourceManager.GetString("lbl_TitleCreateCustomer", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderCategoryName {
            get {
                return ResourceManager.GetString("lbl_PlaceholderCategoryName", resourceCulture);
            }
        }
        
        public static string lbl_TitleEditCateogory {
            get {
                return ResourceManager.GetString("lbl_TitleEditCateogory", resourceCulture);
            }
        }
        
        public static string lbl_TitleCreateCateogory {
            get {
                return ResourceManager.GetString("lbl_TitleCreateCateogory", resourceCulture);
            }
        }
        
        public static string msg_NewCategorySuccess {
            get {
                return ResourceManager.GetString("msg_NewCategorySuccess", resourceCulture);
            }
        }
        
        public static string err_NewCateogory {
            get {
                return ResourceManager.GetString("err_NewCateogory", resourceCulture);
            }
        }
        
        public static string msg_EditCategorySuccess {
            get {
                return ResourceManager.GetString("msg_EditCategorySuccess", resourceCulture);
            }
        }
        
        public static string err_EditCategory {
            get {
                return ResourceManager.GetString("err_EditCategory", resourceCulture);
            }
        }
        
        public static string msg_DeleteCategorySuccess {
            get {
                return ResourceManager.GetString("msg_DeleteCategorySuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteCategory {
            get {
                return ResourceManager.GetString("err_DeleteCategory", resourceCulture);
            }
        }
        
        public static string msg_AlreadyExists {
            get {
                return ResourceManager.GetString("msg_AlreadyExists", resourceCulture);
            }
        }
        
        public static string msg_CategoryNameNotNull {
            get {
                return ResourceManager.GetString("msg_CategoryNameNotNull", resourceCulture);
            }
        }
    }
}
