//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_Action {
            get {
                return ResourceManager.GetString("lbl_Action", resourceCulture);
            }
        }
        
        public static string msg_QuestionDelete {
            get {
                return ResourceManager.GetString("msg_QuestionDelete", resourceCulture);
            }
        }
        
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        public static string btn_Create {
            get {
                return ResourceManager.GetString("btn_Create", resourceCulture);
            }
        }
        
        public static string btn_Back {
            get {
                return ResourceManager.GetString("btn_Back", resourceCulture);
            }
        }
        
        public static string lbl_Find {
            get {
                return ResourceManager.GetString("lbl_Find", resourceCulture);
            }
        }
        
        public static string lbl_NotData {
            get {
                return ResourceManager.GetString("lbl_NotData", resourceCulture);
            }
        }
        
        public static string lbl_NumericalOrder {
            get {
                return ResourceManager.GetString("lbl_NumericalOrder", resourceCulture);
            }
        }
        
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        public static string ImportExcel {
            get {
                return ResourceManager.GetString("ImportExcel", resourceCulture);
            }
        }
        
        public static string lbl_File {
            get {
                return ResourceManager.GetString("lbl_File", resourceCulture);
            }
        }
    }
}
