//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_Address {
            get {
                return ResourceManager.GetString("lbl_Address", resourceCulture);
            }
        }
        
        public static string lbl_Bachelor_sDegree {
            get {
                return ResourceManager.GetString("lbl_Bachelor\'sDegree", resourceCulture);
            }
        }
        
        public static string lbl_BecomeMember {
            get {
                return ResourceManager.GetString("lbl_BecomeMember", resourceCulture);
            }
        }
        
        public static string lbl_Bulid {
            get {
                return ResourceManager.GetString("lbl_Bulid", resourceCulture);
            }
        }
        
        public static string lbl_CompleteCompany {
            get {
                return ResourceManager.GetString("lbl_CompleteCompany", resourceCulture);
            }
        }
        
        public static string lbl_CurrentGoals {
            get {
                return ResourceManager.GetString("lbl_CurrentGoals", resourceCulture);
            }
        }
        
        public static string lbl_CurriculumVitae {
            get {
                return ResourceManager.GetString("lbl_CurriculumVitae", resourceCulture);
            }
        }
        
        public static string lbl_Degree {
            get {
                return ResourceManager.GetString("lbl_Degree", resourceCulture);
            }
        }
        
        public static string lbl_Education {
            get {
                return ResourceManager.GetString("lbl_Education", resourceCulture);
            }
        }
        
        public static string lbl_English {
            get {
                return ResourceManager.GetString("lbl_English", resourceCulture);
            }
        }
        
        public static string lbl_Experience {
            get {
                return ResourceManager.GetString("lbl_Experience", resourceCulture);
            }
        }
        
        public static string lbl_FutureGoals {
            get {
                return ResourceManager.GetString("lbl_FutureGoals", resourceCulture);
            }
        }
        
        public static string lbl_GetCollege {
            get {
                return ResourceManager.GetString("lbl_GetCollege", resourceCulture);
            }
        }
        
        public static string lbl_Graduation {
            get {
                return ResourceManager.GetString("lbl_Graduation", resourceCulture);
            }
        }
        
        public static string lbl_Great {
            get {
                return ResourceManager.GetString("lbl_Great", resourceCulture);
            }
        }
        
        public static string lbl_Information {
            get {
                return ResourceManager.GetString("lbl_Information", resourceCulture);
            }
        }
        
        public static string lbl_InformationTechnology {
            get {
                return ResourceManager.GetString("lbl_InformationTechnology", resourceCulture);
            }
        }
        
        public static string lbl_Interns {
            get {
                return ResourceManager.GetString("lbl_Interns", resourceCulture);
            }
        }
        
        public static string lbl_LeaderCompany {
            get {
                return ResourceManager.GetString("lbl_LeaderCompany", resourceCulture);
            }
        }
        
        public static string lbl_Learn {
            get {
                return ResourceManager.GetString("lbl_Learn", resourceCulture);
            }
        }
        
        public static string lbl_LearnLanguage {
            get {
                return ResourceManager.GetString("lbl_LearnLanguage", resourceCulture);
            }
        }
        
        public static string lbl_Listen {
            get {
                return ResourceManager.GetString("lbl_Listen", resourceCulture);
            }
        }
        
        public static string lbl_Read {
            get {
                return ResourceManager.GetString("lbl_Read", resourceCulture);
            }
        }
        
        public static string lbl_Skill {
            get {
                return ResourceManager.GetString("lbl_Skill", resourceCulture);
            }
        }
        
        public static string lbl_Speak {
            get {
                return ResourceManager.GetString("lbl_Speak", resourceCulture);
            }
        }
        
        public static string lbl_Specialized {
            get {
                return ResourceManager.GetString("lbl_Specialized", resourceCulture);
            }
        }
        
        public static string lbl_Target {
            get {
                return ResourceManager.GetString("lbl_Target", resourceCulture);
            }
        }
        
        public static string lbl_TitleHome {
            get {
                return ResourceManager.GetString("lbl_TitleHome", resourceCulture);
            }
        }
        
        public static string lbl_University {
            get {
                return ResourceManager.GetString("lbl_University", resourceCulture);
            }
        }
        
        public static string lbl_Welcome {
            get {
                return ResourceManager.GetString("lbl_Welcome", resourceCulture);
            }
        }
        
        public static string lbl_Write {
            get {
                return ResourceManager.GetString("lbl_Write", resourceCulture);
            }
        }
    }
}
