//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.LoginResource", typeof(LoginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_Login {
            get {
                return ResourceManager.GetString("lbl_Login", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderEmail {
            get {
                return ResourceManager.GetString("lbl_PlaceholderEmail", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderPassword {
            get {
                return ResourceManager.GetString("lbl_PlaceholderPassword", resourceCulture);
            }
        }
        
        public static string lbl_Language {
            get {
                return ResourceManager.GetString("lbl_Language", resourceCulture);
            }
        }
        
        public static string msg_FormatEmail {
            get {
                return ResourceManager.GetString("msg_FormatEmail", resourceCulture);
            }
        }
        
        public static string msg_LetterAndNumber {
            get {
                return ResourceManager.GetString("msg_LetterAndNumber", resourceCulture);
            }
        }
        
        public static string msg_Min6Characters {
            get {
                return ResourceManager.GetString("msg_Min6Characters", resourceCulture);
            }
        }
        
        public static string msg_PasswordNotNull {
            get {
                return ResourceManager.GetString("msg_PasswordNotNull", resourceCulture);
            }
        }
        
        public static string msg_EmailNotNull {
            get {
                return ResourceManager.GetString("msg_EmailNotNull", resourceCulture);
            }
        }
        
        public static string err_Login {
            get {
                return ResourceManager.GetString("err_Login", resourceCulture);
            }
        }
        
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
    }
}
