//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.ProductResource", typeof(ProductResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_TitleProduct {
            get {
                return ResourceManager.GetString("lbl_TitleProduct", resourceCulture);
            }
        }
        
        public static string lbl_TitleEditProduct {
            get {
                return ResourceManager.GetString("lbl_TitleEditProduct", resourceCulture);
            }
        }
        
        public static string lbl_TitleCreateProduct {
            get {
                return ResourceManager.GetString("lbl_TitleCreateProduct", resourceCulture);
            }
        }
        
        public static string lbl_ProductName {
            get {
                return ResourceManager.GetString("lbl_ProductName", resourceCulture);
            }
        }
        
        public static string lbl_BrandName {
            get {
                return ResourceManager.GetString("lbl_BrandName", resourceCulture);
            }
        }
        
        public static string lbl_CategoryName {
            get {
                return ResourceManager.GetString("lbl_CategoryName", resourceCulture);
            }
        }
        
        public static string lbl_ModelYear {
            get {
                return ResourceManager.GetString("lbl_ModelYear", resourceCulture);
            }
        }
        
        public static string lbl_ListPrice {
            get {
                return ResourceManager.GetString("lbl_ListPrice", resourceCulture);
            }
        }
        
        public static string lbl_Picture {
            get {
                return ResourceManager.GetString("lbl_Picture", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderPoductName {
            get {
                return ResourceManager.GetString("lbl_PlaceholderPoductName", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderModelYear {
            get {
                return ResourceManager.GetString("lbl_PlaceholderModelYear", resourceCulture);
            }
        }
        
        public static string lbl_Example {
            get {
                return ResourceManager.GetString("lbl_Example", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderListPrice {
            get {
                return ResourceManager.GetString("lbl_PlaceholderListPrice", resourceCulture);
            }
        }
        
        public static string lbl_Products {
            get {
                return ResourceManager.GetString("lbl_Products", resourceCulture);
            }
        }
        
        public static string msg_NewProductSuccess {
            get {
                return ResourceManager.GetString("msg_NewProductSuccess", resourceCulture);
            }
        }
        
        public static string err_NewProduct {
            get {
                return ResourceManager.GetString("err_NewProduct", resourceCulture);
            }
        }
        
        public static string msg_EditProductSuccess {
            get {
                return ResourceManager.GetString("msg_EditProductSuccess", resourceCulture);
            }
        }
        
        public static string err_EditProduct {
            get {
                return ResourceManager.GetString("err_EditProduct", resourceCulture);
            }
        }
        
        public static string msg_EditImageProductSuccess {
            get {
                return ResourceManager.GetString("msg_EditImageProductSuccess", resourceCulture);
            }
        }
        
        public static string err_EditImageProduct {
            get {
                return ResourceManager.GetString("err_EditImageProduct", resourceCulture);
            }
        }
        
        public static string msg_DeleteProductSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteProductSuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteProduct {
            get {
                return ResourceManager.GetString("err_DeleteProduct", resourceCulture);
            }
        }
        
        public static string msg_AlreadyExists {
            get {
                return ResourceManager.GetString("msg_AlreadyExists", resourceCulture);
            }
        }
        
        public static string msg_ProductNameNotNull {
            get {
                return ResourceManager.GetString("msg_ProductNameNotNull", resourceCulture);
            }
        }
        
        public static string msg_ListPriceNotNull {
            get {
                return ResourceManager.GetString("msg_ListPriceNotNull", resourceCulture);
            }
        }
        
        public static string msg_ModelYearNotNull {
            get {
                return ResourceManager.GetString("msg_ModelYearNotNull", resourceCulture);
            }
        }
        
        public static string msg_PictureFileNotNull {
            get {
                return ResourceManager.GetString("msg_PictureFileNotNull", resourceCulture);
            }
        }
        
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
    }
}
