//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StockResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.StockResource", typeof(StockResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_TitleStock {
            get {
                return ResourceManager.GetString("lbl_TitleStock", resourceCulture);
            }
        }
        
        public static string lbl_Stocks {
            get {
                return ResourceManager.GetString("lbl_Stocks", resourceCulture);
            }
        }
        
        public static string lbl_StoreName {
            get {
                return ResourceManager.GetString("lbl_StoreName", resourceCulture);
            }
        }
        
        public static string lbl_ProductName {
            get {
                return ResourceManager.GetString("lbl_ProductName", resourceCulture);
            }
        }
        
        public static string lbl_Quantity {
            get {
                return ResourceManager.GetString("lbl_Quantity", resourceCulture);
            }
        }
        
        public static string lbl_TitleEditStock {
            get {
                return ResourceManager.GetString("lbl_TitleEditStock", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderQuantity {
            get {
                return ResourceManager.GetString("lbl_PlaceholderQuantity", resourceCulture);
            }
        }
        
        public static string lbl_TitleCreateStock {
            get {
                return ResourceManager.GetString("lbl_TitleCreateStock", resourceCulture);
            }
        }
        
        public static string msg_NewStockSuccess {
            get {
                return ResourceManager.GetString("msg_NewStockSuccess", resourceCulture);
            }
        }
        
        public static string err_NewStock {
            get {
                return ResourceManager.GetString("err_NewStock", resourceCulture);
            }
        }
        
        public static string msg_EditStockSuccess {
            get {
                return ResourceManager.GetString("msg_EditStockSuccess", resourceCulture);
            }
        }
        
        public static string err_EditStock {
            get {
                return ResourceManager.GetString("err_EditStock", resourceCulture);
            }
        }
        
        public static string msg_DeleteStockSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteStockSuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteStock {
            get {
                return ResourceManager.GetString("err_DeleteStock", resourceCulture);
            }
        }
        
        public static string msg_QuantityNotNull {
            get {
                return ResourceManager.GetString("msg_QuantityNotNull", resourceCulture);
            }
        }
        
        public static string msg_GreaterThan0 {
            get {
                return ResourceManager.GetString("msg_GreaterThan0", resourceCulture);
            }
        }
    }
}
