//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.StoreResource", typeof(StoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_TitleStore {
            get {
                return ResourceManager.GetString("lbl_TitleStore", resourceCulture);
            }
        }
        
        public static string lbl_Stores {
            get {
                return ResourceManager.GetString("lbl_Stores", resourceCulture);
            }
        }
        
        public static string lbl_StoreName {
            get {
                return ResourceManager.GetString("lbl_StoreName", resourceCulture);
            }
        }
        
        public static string lbl_Phone {
            get {
                return ResourceManager.GetString("lbl_Phone", resourceCulture);
            }
        }
        
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        public static string lbl_Street {
            get {
                return ResourceManager.GetString("lbl_Street", resourceCulture);
            }
        }
        
        public static string lbl_City {
            get {
                return ResourceManager.GetString("lbl_City", resourceCulture);
            }
        }
        
        public static string lbl_State {
            get {
                return ResourceManager.GetString("lbl_State", resourceCulture);
            }
        }
        
        public static string lbl_ZipCode {
            get {
                return ResourceManager.GetString("lbl_ZipCode", resourceCulture);
            }
        }
        
        public static string lbl_TitleEditStore {
            get {
                return ResourceManager.GetString("lbl_TitleEditStore", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderEmail {
            get {
                return ResourceManager.GetString("lbl_PlaceholderEmail", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderStoreName {
            get {
                return ResourceManager.GetString("lbl_PlaceholderStoreName", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderPhone {
            get {
                return ResourceManager.GetString("lbl_PlaceholderPhone", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderStreet {
            get {
                return ResourceManager.GetString("lbl_PlaceholderStreet", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderCity {
            get {
                return ResourceManager.GetString("lbl_PlaceholderCity", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderZipCode {
            get {
                return ResourceManager.GetString("lbl_PlaceholderZipCode", resourceCulture);
            }
        }
        
        public static string lbl_TitleCreateStore {
            get {
                return ResourceManager.GetString("lbl_TitleCreateStore", resourceCulture);
            }
        }
        
        public static string msg_NewStoreSuccess {
            get {
                return ResourceManager.GetString("msg_NewStoreSuccess", resourceCulture);
            }
        }
        
        public static string err_NewStore {
            get {
                return ResourceManager.GetString("err_NewStore", resourceCulture);
            }
        }
        
        public static string msg_EditStoreSuccess {
            get {
                return ResourceManager.GetString("msg_EditStoreSuccess", resourceCulture);
            }
        }
        
        public static string err_EditStore {
            get {
                return ResourceManager.GetString("err_EditStore", resourceCulture);
            }
        }
        
        public static string msg_DeleteStoreSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteStoreSuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteStore {
            get {
                return ResourceManager.GetString("err_DeleteStore", resourceCulture);
            }
        }
        
        public static string msg_AlreadyExists {
            get {
                return ResourceManager.GetString("msg_AlreadyExists", resourceCulture);
            }
        }
        
        public static string msg_StoreNameNotNull {
            get {
                return ResourceManager.GetString("msg_StoreNameNotNull", resourceCulture);
            }
        }
        
        public static string msg_PhoneNotNull {
            get {
                return ResourceManager.GetString("msg_PhoneNotNull", resourceCulture);
            }
        }
        
        public static string msg_EmailNotNull {
            get {
                return ResourceManager.GetString("msg_EmailNotNull", resourceCulture);
            }
        }
        
        public static string msg_FormatEmail {
            get {
                return ResourceManager.GetString("msg_FormatEmail", resourceCulture);
            }
        }
        
        public static string msg_StreetNotNull {
            get {
                return ResourceManager.GetString("msg_StreetNotNull", resourceCulture);
            }
        }
        
        public static string msg_CityNotNull {
            get {
                return ResourceManager.GetString("msg_CityNotNull", resourceCulture);
            }
        }
        
        public static string msg_ZipCodeNotNull {
            get {
                return ResourceManager.GetString("msg_ZipCodeNotNull", resourceCulture);
            }
        }
    }
}
