//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_TitleUser {
            get {
                return ResourceManager.GetString("lbl_TitleUser", resourceCulture);
            }
        }
        
        public static string lbl_TitleEditUser {
            get {
                return ResourceManager.GetString("lbl_TitleEditUser", resourceCulture);
            }
        }
        
        public static string lbl_TitleCreateUser {
            get {
                return ResourceManager.GetString("lbl_TitleCreateUser", resourceCulture);
            }
        }
        
        public static string lbl_Users {
            get {
                return ResourceManager.GetString("lbl_Users", resourceCulture);
            }
        }
        
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        public static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        public static string lbl_FullName {
            get {
                return ResourceManager.GetString("lbl_FullName", resourceCulture);
            }
        }
        
        public static string lbl_Phone {
            get {
                return ResourceManager.GetString("lbl_Phone", resourceCulture);
            }
        }
        
        public static string lbl_Picture {
            get {
                return ResourceManager.GetString("lbl_Picture", resourceCulture);
            }
        }
        
        public static string lbl_Address {
            get {
                return ResourceManager.GetString("lbl_Address", resourceCulture);
            }
        }
        
        public static string lbl_IsActive {
            get {
                return ResourceManager.GetString("lbl_IsActive", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderEmail {
            get {
                return ResourceManager.GetString("lbl_PlaceholderEmail", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderPassword {
            get {
                return ResourceManager.GetString("lbl_PlaceholderPassword", resourceCulture);
            }
        }
        
        public static string lbl_StoreName {
            get {
                return ResourceManager.GetString("lbl_StoreName", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderFullName {
            get {
                return ResourceManager.GetString("lbl_PlaceholderFullName", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderPhone {
            get {
                return ResourceManager.GetString("lbl_PlaceholderPhone", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderAddress {
            get {
                return ResourceManager.GetString("lbl_PlaceholderAddress", resourceCulture);
            }
        }
        
        public static string msg_NewUserSuccess {
            get {
                return ResourceManager.GetString("msg_NewUserSuccess", resourceCulture);
            }
        }
        
        public static string err_NewUser {
            get {
                return ResourceManager.GetString("err_NewUser", resourceCulture);
            }
        }
        
        public static string msg_EditUserSuccess {
            get {
                return ResourceManager.GetString("msg_EditUserSuccess", resourceCulture);
            }
        }
        
        public static string err_EditUser {
            get {
                return ResourceManager.GetString("err_EditUser", resourceCulture);
            }
        }
        
        public static string msg_EditUserPasswordSuccess {
            get {
                return ResourceManager.GetString("msg_EditUserPasswordSuccess", resourceCulture);
            }
        }
        
        public static string err_EditUserPassword {
            get {
                return ResourceManager.GetString("err_EditUserPassword", resourceCulture);
            }
        }
        
        public static string msg_DeleteUserSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteUserSuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteUser {
            get {
                return ResourceManager.GetString("err_DeleteUser", resourceCulture);
            }
        }
        
        public static string err_Login {
            get {
                return ResourceManager.GetString("err_Login", resourceCulture);
            }
        }
        
        public static string msg_NewPasswordNotNull {
            get {
                return ResourceManager.GetString("msg_NewPasswordNotNull", resourceCulture);
            }
        }
        
        public static string msg_ConfirmPasswordNotNull {
            get {
                return ResourceManager.GetString("msg_ConfirmPasswordNotNull", resourceCulture);
            }
        }
        
        public static string msg_EqualPassword {
            get {
                return ResourceManager.GetString("msg_EqualPassword", resourceCulture);
            }
        }
        
        public static string msg_AlreadyExists {
            get {
                return ResourceManager.GetString("msg_AlreadyExists", resourceCulture);
            }
        }
        
        public static string msg_FullNameNotNull {
            get {
                return ResourceManager.GetString("msg_FullNameNotNull", resourceCulture);
            }
        }
        
        public static string msg_ToOneFromOneHundred {
            get {
                return ResourceManager.GetString("msg_ToOneFromOneHundred", resourceCulture);
            }
        }
        
        public static string msg_PhoneNotNull {
            get {
                return ResourceManager.GetString("msg_PhoneNotNull", resourceCulture);
            }
        }
        
        public static string msg_PictureNotNull {
            get {
                return ResourceManager.GetString("msg_PictureNotNull", resourceCulture);
            }
        }
        
        public static string msg_IsActiveNotNull {
            get {
                return ResourceManager.GetString("msg_IsActiveNotNull", resourceCulture);
            }
        }
        
        public static string msg_AddressNotNull {
            get {
                return ResourceManager.GetString("msg_AddressNotNull", resourceCulture);
            }
        }
        
        public static string msg_FormatEmail {
            get {
                return ResourceManager.GetString("msg_FormatEmail", resourceCulture);
            }
        }
        
        public static string msg_LetterAndNumber {
            get {
                return ResourceManager.GetString("msg_LetterAndNumber", resourceCulture);
            }
        }
        
        public static string msg_Min6Characters {
            get {
                return ResourceManager.GetString("msg_Min6Characters", resourceCulture);
            }
        }
        
        public static string msg_PasswordNotNull {
            get {
                return ResourceManager.GetString("msg_PasswordNotNull", resourceCulture);
            }
        }
        
        public static string msg_EmailNotNull {
            get {
                return ResourceManager.GetString("msg_EmailNotNull", resourceCulture);
            }
        }
        
        public static string lbl_EditPasswordUser {
            get {
                return ResourceManager.GetString("lbl_EditPasswordUser", resourceCulture);
            }
        }
        
        public static string lbl_NewPassword {
            get {
                return ResourceManager.GetString("lbl_NewPassword", resourceCulture);
            }
        }
        
        public static string lbl_ConfirmPassword {
            get {
                return ResourceManager.GetString("lbl_ConfirmPassword", resourceCulture);
            }
        }
        
        public static string lbl_PlaceholderNewPassword {
            get {
                return ResourceManager.GetString("lbl_PlaceholderNewPassword", resourceCulture);
            }
        }
        
        public static string pld_PlaceholderConfirmPassword {
            get {
                return ResourceManager.GetString("pld_PlaceholderConfirmPassword", resourceCulture);
            }
        }
        
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        public static string lbl_RoleName {
            get {
                return ResourceManager.GetString("lbl_RoleName", resourceCulture);
            }
        }
    }
}
