//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTranning.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewLayoutResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewLayoutResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TaskTranning.Resources.ViewLayoutResource", typeof(ViewLayoutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string btn_Home {
            get {
                return ResourceManager.GetString("btn_Home", resourceCulture);
            }
        }
        
        public static string lbl_Hello {
            get {
                return ResourceManager.GetString("lbl_Hello", resourceCulture);
            }
        }
        
        public static string btn_LogOut {
            get {
                return ResourceManager.GetString("btn_LogOut", resourceCulture);
            }
        }
        
        public static string btn_Management {
            get {
                return ResourceManager.GetString("btn_Management", resourceCulture);
            }
        }
        
        public static string btn_User {
            get {
                return ResourceManager.GetString("btn_User", resourceCulture);
            }
        }
        
        public static string btn_Store {
            get {
                return ResourceManager.GetString("btn_Store", resourceCulture);
            }
        }
        
        public static string btn_Customer {
            get {
                return ResourceManager.GetString("btn_Customer", resourceCulture);
            }
        }
        
        public static string btn_Category {
            get {
                return ResourceManager.GetString("btn_Category", resourceCulture);
            }
        }
        
        public static string btn_Product {
            get {
                return ResourceManager.GetString("btn_Product", resourceCulture);
            }
        }
        
        public static string btn_Brand {
            get {
                return ResourceManager.GetString("btn_Brand", resourceCulture);
            }
        }
        
        public static string btn_Stock {
            get {
                return ResourceManager.GetString("btn_Stock", resourceCulture);
            }
        }
    }
}
